### ISSUE TITLE
SOLID 원칙 약자가 잘못되어 있습니다.

### ISSUE THREAD

**Issue by coplayer** [WeareSoft/tech-interview#40]
I랑 D랑 바뀌어 있네요 😲

**Comment by NESOY** [comment]
@coplayer 
관련 내용 수정해서 Contribution 해보시는건 어떠실까요?

**Comment by coplayer** [comment]
동기화 되어 있다는 블로그의 내용은 변경이 되지 앉아 있었네요. 클론 내용은 정상이었습니다.

좋은 레포 참고하고 갑니다 :) 👍
